Custom field and observation types
panoptes/POCS pull request #1103
Opened 2021-04-12 06:56 UTC by danjampro

Adds functionality to use custom `Field` and `Observation` objects using the existing `Scheduler` paradigm. The existing types `panoptes.pocs.scheduler.field.Field` and `panoptes.pocs.scheduler.observation.base.Observation` are used by default, but can be overridden in the targets file.

This requires a format change to the targets file to add the `field` and `observation` keys. This seems like the best method of creating generic `Field` and `Observation` objects from a config file. 

Also this PR renames `fields_list` and `fields_file` to `targets_list` and `targets_file`, making it more consistent with the rest of `POCS` (e.g. `targets.yaml`, directories.targets` etc).

This will pave the way for scheduling of things like calibs and other observations that do not work with the standard `Field/Observation`.

## How Has This Been Tested?
Unit tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

2021-04-12 22:01 UTC, wtgee requested changes
Thanks @danjampro. I'm a little torn on the renaming of everything to `targets` as I think that's a bit the opposite direction from how it should go; namely, everything should be changed toto `fields` where it currently says `target`, e.g. the directory should probably change to `directories.fields`, etc.

The `Observation` has a field, which also has a certain FOV, etc.  It could be said that it is a target field, but more often (at least for exoplanets), our target would probably be the star at the center of the field, which is why there is baked in confusion for POCS right now.

This would also keep it more consistent with the class name and what is in the config.

More practically speaking for requested changes, I don't see any tests of the new `type` field or example in the config.

2021-04-13 01:10 UTC, danjampro commented on src/panoptes/pocs/scheduler/scheduler.py
> +        field_type_name = field_config.pop("type", "panoptes.pocs.scheduler.field.Field")
Docstring added.

2021-04-13 01:10 UTC, danjampro commented on src/panoptes/pocs/scheduler/scheduler.py
> +            "type", "panoptes.pocs.scheduler.observation.base.Observation")
Docstring added.

2021-04-13 01:11 UTC, danjampro commented
> Thanks @danjampro. I'm a little torn on the renaming of everything to `targets` as I think that's a bit the opposite direction from how it should go; namely, everything should be changed toto `fields` where it currently says `target`, e.g. the directory should probably change to `directories.fields`, etc.
> 
> The `Observation` has a field, which also has a certain FOV, etc. It could be said that it is a target field, but more often (at least for exoplanets), our target would probably be the star at the center of the field, which is why there is baked in confusion for POCS right now.
> 
> This would also keep it more consistent with the class name and what is in the config.
> 
> More practically speaking for requested changes, I don't see any tests of the new `type` field or example in the config.

@wtgee thanks for the review! I have reverted to the old "fields" naming as well as renamed `directories.targets` to `directories.fields`. I have also updated the docstrings accordingly.

2021-04-13 19:57 UTC, wtgee approved these changes
👍🏼 thanks for addressing those changes and adding the new feature!

2021-04-13 19:57 UTC, merged